# copyright © 2017 the libfulltext authors (see AUTHORS.md and LICENSE)

sudo: false
language: python
cache: pip
python:
  - "3.5"
  - "3.6"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install nose2 pylint flake8

script:  # This is the 'test' build stage
  - nose2 --with-coverage
    # Fail if coverage below threshold
  - python3 -m coverage report --fail-under=55 > /dev/null
  - pip install ${TRAVIS_BUILD_DIR}

after_success:
  - echo Success  # TODO upload coverage

# These jobs are only run with the first python version
# mentioned in the initial list.
jobs:
  include:
    - stage: code style
      script: pylint bin libfulltext
      env: CODE_STYLE="pylint"
    - script: flake8
      env: CODE_STYLE="flake8"
    #
    - stage: deploy
      # TODO deploy to pip
      script: skip

stages:
  - code style
  - test
  - name: deploy
    if: branch = master AND type = push
