# copyright © 2017 the libfulltext authors (see AUTHORS.md and LICENSE)

language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - pip install -r requirements.txt
    - pip install pylint nose2
script:
    - pylint bin libfulltext
    - nose2
