# copyright © 2017 the libfulltext authors (see AUTHORS.md and LICENSE)

language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - pip install -r requirements.txt
    - pip install pylint
script:
    - pylint bin libfulltext
after_success:
    - pip install ${TRAVIS_BUILD_DIR}
