storage:
  fulltext:
    type: Directory
    default: "./fulltext"
    description: "Fulltext document root storage directory"

publishers:
  elsevier:
    apikey:
      type: String
      required: True
      description: "Elsevier API key."
